server:
  port: 10082
spring:
  application:
    name: gateway
eureka:
  instance:
    # 服务续约的两个重要属性
    leaseRenewalIntervalInSeconds: 30 # 服务续约间隔时间。默认每隔30秒，客户端会向服务端发送心跳。
    leaseExpirationDurationInSeconds: 90 # 服务失效时间。缺省为90秒服务端接收不到客户端的心跳，则剔除该客户端服务实例。
  client:
    service-url:
      defaultZone: http://127.0.0.1:10080/eureka/ #应用的主机名称
    # 是否启用eureka客户端。默认true
    enabled: true # 本地调试时，若不想启动eureka，可配置false即可，而不需要注释掉@EnableDiscoveryClient这么麻烦。
    # 缓存清单更新时间，默认30秒。见EurekaClientConfigBean，其中DefaultEurekaClientConfig可不看（前者spring实现，后者Netflix实现）
    registry-fetch-interval-seconds: 30 # 如果想eureka server剔除服务后尽快在client体现，我觉得可缩短此时间。
    healthcheck:
      enabled: true
zuul:
  # 路由规则
  routes:
    system-shop: /system/** # 路由到 system 微服务
  # 是否开启重试 开启需要引入spring-retry
  retryable: false
  # 设置全局访问的前缀，配置之后所有请求前缀需要加上/api
  prefix: /api
  host:
    # 最大连接数，默认为200
    max-total-connections: 200
    # 单个路由可以使用的最大连接数，默认为20
    max-per-route-connections: 20
    # http client中从connection pool中获得一个connection的超时时间，默认为-1，不超时
    connection-request-timeout-millis: -1
    # 连接建立的超时时间；，默认为2000ms
    connect-timeout-millis: 2000
    # 响应超时时间，默认为10000ms
    socket-timeout-millis: 10000

