server:
  port: 10080
spring:
  application:
    name: registry
eureka:
  instance:
    # 心跳间隔，5秒
    lease-renewal-interval-in-seconds: 5
    # 没有心跳的淘汰时间，10秒
    lease-expiration-duration-in-seconds: 10
  client:
    # 设置 与 eureka server 交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/ #应用的主机名称
    # false 表示不向注册中心注册自己
    register-with-eureka: false
    # false 表示自己就是注册中心，就是维护服务实例，不需要检索服务
    fetch-registry: false
    # 检测服务的时间，单位秒
    eureka-server-read-timeout-seconds: 30
    # 开启健康监测
    healthcheck:
      enabled: true
  server:
    # 关闭自我保护机制，保证不可用服务被及时剔除
    enable-self-preservation: false # 本地调试时可fasle关闭。但生产建议打开，可防止因网络不稳定等原因导致误剔除服务。
    # 启用主动失效，并且每次主动失效检测间隔为3s。源码evictionIntervalTimerInMs = 60 * 1000，默认一分钟。
    # 需要注意的是该配置会打印INFO日志，增加info日志量，修改后从每60秒打印一次变成3秒打印一次。
    eviction-interval-timer-in-ms: 3000
    # eureka服务端 记录client的身份header
    log-identity-headers: true
    # 默认85%
    renewal-percent-threshold: 0.85
    # 在服务器接收请求之前等待的初始时间，默认等待5min
    wait-time-in-ms-when-sync-empty: 5 # John说开发时最好注释此配置，服务注册需要3次心跳，每次10s，也就是30s才能显示在eureka。
    # eureka server刷新readCacheMap的时间，注意，client读取的是readCacheMap，这个时间决定了多久会把readWriteCacheMap的缓存更新到readCacheMap上
    # 默认30秒，eclipse提示默认0应该是错误的，源代码中responseCacheUpdateIntervalMs = 30 * 1000。
    response-cache-update-interval-ms: 3000
    # 由于启用了evict其实就用不太上改这个配置了，默认180s
    response-cache-auto-expiration-in-seconds: 180


